---
title: "R Notebook"
output: 
---

```{r}
library(tidyverse)
library(tidycensus)
library(janitor)
library(lubridate)
library(transformr)
library(rjson)
```


```{r}
mo_counties <- get_estimates(geography = "county",
                             state = "mo",
                             product = "population",
                             geometry = T,
                             cb = T)
```


```{r}
stds <- read_csv("/Users/coles/Documents/spring_23/graphicsdesk/data/all_counties_stds.csv")

summary(stds)
```


```{r}
syphilis<- stds %>% mutate(
  county=tolower(county), 
  diagnosis=tolower(diagnosis)) %>%
  pivot_longer(-c(1:3), names_to = "month", values_to = "value") %>% 
  mutate(date =  ym(paste0(year, month))) %>%
  filter(month != "total",
         diagnosis == "syphilis") %>% 
  select(county, date, value) %>%
  group_by(date) %>% 
  summarise(value = sum(value)) %>%


syphilis_cum_sum<- stds %>% mutate(
  county=tolower(county), 
  diagnosis=tolower(diagnosis)) %>%
  pivot_longer(-c(1:3), names_to = "month", values_to = "value") %>% 
  mutate(date =  ym(paste0(year, month))) %>%
  filter(month != "total",
         diagnosis == "syphilis") %>% 
  select(county, date, value) %>%
  group_by(date) %>% 
  summarise(value = sum(value)) %>% 
  mutate(value=cumsum(value))
   
```


```{r}
mo_counties <- get_estimates(geography = "county",
                             state = "mo",
                             product = "population")

mo_counties <- mo_counties %>% 
  clean_names() %>% 
  mutate(name=ifelse(grepl("County", name), str_extract(name, ".*(?= County)"), "st louis city")) %>% mutate(value = round(as.numeric(value)), county = tolower(str_replace(name,"\\.",""))) 

syphilis_counties <- stds %>% mutate(
  county=tolower(county), 
  diagnosis=tolower(diagnosis)) %>%
  pivot_longer(-c(1:3), names_to = "month", values_to = "value") %>% 
  filter(month != "total",
         diagnosis == "syphilis") %>% 
  mutate(date =  ym(paste0(year, month))) %>%
  select(county, date, value) %>%
  #filter(date==ymd("2022-12-01")) %>% 
  right_join(mo_counties %>% filter(variable == "POP"), by="county") %>% 
  mutate(per_capita = (100000*value.x)/value.y) %>%
  select(date, geoid, per_capita) %>% 
  pivot_wider(names_from = "geoid", values_from = "per_capita") %>%
  arrange(date) %>% 
  mutate_if(is.numeric, ~replace_na(., 0)) %>% 
  mutate_if(is.numeric, cumsum) %>% 
  pivot_longer(-c(date), names_to = "geoid", values_to = "value") %>% 
  #select(date, geoid, cum_sum) %>%
  #filter(date != "NA") %>%
  pivot_wider(names_from = "date", values_from = "value")
  #pivot_longer(-c(geoid), names_to = "date", values_to = "value")

summary(syphilis_counties)

write_csv(syphilis_counties, "/Users/coles/Documents/spring_23/graphicsdesk/app/src/routes/missouri-syphilis-dashboard/data/cum_sum_per_capita_counties.csv")

json = toJSON(syphilis_counties)
write(json, "/Users/coles/Documents/spring_23/graphicsdesk/app/src/routes/data.json")
```


